Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'
urlpatterns = [
    path('', views.cart, name='cart'),
]

Contact/urls.py
from django.urls import path
from . import views

app_name = 'Contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home'),
]

Shop/urls.py
from django.urls import path
from . import views

app_name = 'Shop'
urlpatterns = [
    path('category', views.category, name='shop'),
]

api/urls.py
from django.urls import path
from . import api

app_name = 'api'
urlpatterns = [
    path('products', api.ProductsList.as_view()),
    path('products/lommentslist', api.CommentsList.as_view()),
    path('products/comments/reblylist', api.ReblyList.as_view()),
    path('products/ratinglist', api.RatingList.as_view()),
    path('cart', api.CartList.as_view()),
    path('profile', api.ProfileList.as_view()),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Home.urls', namespace= 'Home')),
    path('shop/', include('Shop.urls', namespace= 'shop')),
    path('shop/', include('Product_Details.urls', namespace='Product_Details')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('Cart.urls', namespace='Cart')),
    path('contact/', include('Contact.urls', namespace='Contact')),
    path('api/', include('api.urls', namespace='api')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Contact/views.py
from django.conf import settings
from django.shortcuts import render
from django.core.mail import send_mail
from Home.models import Cart

# Create your views here.
def contact(request):
    carts= Cart.objects.all()
    if request.method== "POST" and "contact_request" in request.POST:
        name = request.POST['name']
        subject = request.POST['subject']
        message = request.POST['message']
        email = request.POST['email']
        send_mail(
            f"{subject} ,Contact from {name}",
            message,
            email,
            [settings.EMAIL_HOST_USER],
        )
    
    context={'carts': carts}
    return render(request, 'Contact/contact.html', context)

Contact/templates/Contact/contact.html
{% extends 'contact.html' %}
{% load static %}

{% block body %}
  <!--::header part start::-->
  <header class="main_menu home_menu">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="{% url 'Home:home' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_icon"><i class="fas fa-bars"></i></span>
                    </button>

                    <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Home:home' %}">Home</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Shop
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                    <a class="dropdown-item" href="{% url 'Shop:shop' %}"> shop category</a>
                                    <a class="dropdown-item" href="#">product details</a>
                                    
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    pages
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                    <a class="dropdown-item" href="{% url 'login' %}"> login</a>
                                    <a class="dropdown-item" href="{% url 'Cart:cart' %}">shopping cart</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Contact:contact' %}">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div class="hearer_icon d-flex">
                        <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                        <a href=""><i class="ti-heart"></i></a>
                        <div class="dropdown cart">
                            <a class="dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="single_product">

                                </div>
                            </div> -->
                            
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container ">
            <form class="d-flex justify-content-between search-inner">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="ti-close" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>
  <!-- Header part end-->

  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>contact us</h2>
              <p>Home <span>-</span> contact us</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!-- ================ contact section start ================= -->
  <section class="contact-section padding_top">
    <div class="container">
    <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">

                  <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                    placeholder='Enter Message'></textarea>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter your name'" placeholder='Enter your name'>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter email address'" placeholder='Enter email address'>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter Subject'" placeholder='Enter Subject'>
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <input type="hidden" name="contact_request">
              <input type="submit" class="btn_3 button-contactForm" value="Send Message" name="contact_request">
              <!-- <a href="#" class="btn_3 button-contactForm">Send Message</a> -->
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@colorlib.com</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->
<style>
  .main_menu .cart i::after{
  content: '{{carts.count}}';
}
</style>
{% endblock body %}